package com.example.skillexchange.adapter

class NewSkillsRepository {
    fun getNewSkillsWords(): List<ListItem> {
        return listOf(
            ListItem.MainHeaderItem("Творчество и искусство:"),
            ListItem.HeaderItem("Рисование"),
            ListItem.TextItem("Живопись"),
            ListItem.TextItem("Графика"),
            ListItem.TextItem("Иллюстрации"),
            ListItem.TextItem("Дизайн"),
            ListItem.HeaderItem("Музыка"),
            ListItem.TextItem("Пение"),
            ListItem.TextItem("Игра на музыкальных инструментах"),
            ListItem.TextItem("Композиция"),
            ListItem.HeaderItem("Литература"),
            ListItem.TextItem("Поэзия"),
            ListItem.TextItem("Проза"),
            ListItem.TextItem("Драматургия"),
            ListItem.TextItem("Журналистика"),
            ListItem.HeaderItem("Театр"),
            ListItem.TextItem("Актерское мастерство"),
            ListItem.TextItem("Режиссура"),
            ListItem.TextItem("Сценография"),
            ListItem.HeaderItem("Фотография"),
            ListItem.TextItem("Фотосъемка"),
            ListItem.TextItem("Обработка изображений"),
            ListItem.TextItem("Фоторепортаж"),
            ListItem.HeaderItem("Кино"),
            ListItem.TextItem("Режиссура"),
            ListItem.TextItem("Операторское искусство"),
            ListItem.TextItem("Актерское мастерство"),
            ListItem.TextItem("Сценаристика"),
            ListItem.HeaderItem("Танцы"),
            ListItem.TextItem("Балет"),
            ListItem.TextItem("Современный танец"),
            ListItem.TextItem("Народные танцы"),
            ListItem.TextItem("Бальные танцы"),
            ListItem.HeaderItem("Скульптура"),
            ListItem.TextItem("Лепка"),
            ListItem.TextItem("Резба"),
            ListItem.TextItem("Литье"),
            ListItem.HeaderItem("Дизайн"),
            ListItem.TextItem("Графический"),
            ListItem.TextItem("Веб"),
            ListItem.TextItem("Промышленный"),
            ListItem.TextItem("Интерьерный"),
            ListItem.HeaderItem("Мода"),
            ListItem.TextItem("Дизайн одежды"),
            ListItem.TextItem("Стиль"),
            ListItem.TextItem("Кройка и шитье"),
            ListItem.HeaderItem("Красота и стиль"),
            ListItem.TextItem("Визаж"),
            ListItem.TextItem("Стилистика"),
            ListItem.TextItem("Парикмахерское искусство"),

            ListItem.MainHeaderItem("Технологии и науки:"),
            ListItem.HeaderItem("Программирование"),
            ListItem.TextItem("Разработка программного обеспечения"),
            ListItem.TextItem("Веб-разработка"),
            ListItem.TextItem("Мобильная разработка"),
            ListItem.HeaderItem("Искусственный интеллект"),
            ListItem.TextItem("Машинное обучение"),
            ListItem.TextItem("Глубокое обучение"),
            ListItem.TextItem("Обработка естественного языка"),
            ListItem.HeaderItem("Data Science"),
            ListItem.TextItem("Анализ данных"),
            ListItem.TextItem("Статистика"),
            ListItem.TextItem("Машинное обучение"),
            ListItem.HeaderItem("Кибербезопасность"),
            ListItem.TextItem("Защита информации"),
            ListItem.TextItem("Пентестинг"),
            ListItem.TextItem("Анализ уязвимостей"),
            ListItem.HeaderItem("Инженерные науки"),
            ListItem.HeaderItem("Механика"),
            ListItem.TextItem("Электроника"),
            ListItem.TextItem("Робототехника"),
            ListItem.TextItem("Авиация"),
            ListItem.TextItem("Математика"),
            ListItem.TextItem("Алгебра"),
            ListItem.TextItem("Геометрия"),
            ListItem.TextItem("Математический анализ"),
            ListItem.TextItem("Теория вероятностей"),
            ListItem.HeaderItem("Физика"),
            ListItem.TextItem("Механика"),
            ListItem.TextItem("Термодинамика"),
            ListItem.TextItem("Электродинамика"),
            ListItem.TextItem("Оптика"),
            ListItem.HeaderItem("Химия"),
            ListItem.TextItem("Органическая химия"),
            ListItem.TextItem("Неорганическая химия"),
            ListItem.TextItem("Аналитическая химия"),
            ListItem.HeaderItem("Биология"),
            ListItem.TextItem("Зоология"),
            ListItem.TextItem("Ботаника"),
            ListItem.TextItem("Генетика"),
            ListItem.TextItem("Молекулярная биология"),
            ListItem.HeaderItem("Медицина"),
            ListItem.TextItem("Хирургия"),
            ListItem.TextItem("Терапия"),
            ListItem.TextItem("Педиатрия"),
            ListItem.TextItem("Кардиология"),

            ListItem.MainHeaderItem("Общественные науки и гуманитарные науки:"),
            ListItem.HeaderItem("Психология"),
            ListItem.TextItem("Психология личности"),
            ListItem.TextItem("Социальная психология"),
            ListItem.TextItem("Когнитивная психология"),
            ListItem.HeaderItem("Социология"),
            ListItem.TextItem("Изучение общества"),
            ListItem.TextItem("Социальных институтов"),
            ListItem.TextItem("Социальных процессов"),
            ListItem.HeaderItem("История"),
            ListItem.TextItem("Изучение прошлого"),
            ListItem.TextItem("Исторические события"),
            ListItem.TextItem("Исторические личности"),
            ListItem.HeaderItem("Философия"),
            ListItem.TextItem("Изучение фундаментальных вопросов бытия"),
            ListItem.TextItem("Знания"),
            ListItem.TextItem("Ценностей"),
            ListItem.HeaderItem("Политология"),
            ListItem.TextItem("Изучение политических систем"),
            ListItem.TextItem("Политических процессов"),
            ListItem.TextItem("Политического поведения"),
            ListItem.HeaderItem("Право"),
            ListItem.TextItem("Изучение правовых норм"),
            ListItem.TextItem("Правовых систем"),
            ListItem.TextItem("Правоприменения"),
            ListItem.HeaderItem("Экономика"),
            ListItem.TextItem("Изучение экономических процессов"),
            ListItem.TextItem("Рыночных механизмов"),
            ListItem.TextItem("Макроэкономики"),
            ListItem.TextItem("Микроэкономики"),
            ListItem.HeaderItem("Лингвистика"),
            ListItem.TextItem("Изучение языка"),
            ListItem.TextItem("Языковой структуры"),
            ListItem.TextItem("Языковой эволюции"),
            ListItem.HeaderItem("Педагогика"),
            ListItem.TextItem("Обучение"),
            ListItem.TextItem("Воспитание"),
            ListItem.TextItem("Образовательные технологии"),
            ListItem.HeaderItem("Культурология"),
            ListItem.TextItem("Изучение культуры"),
            ListItem.TextItem("Культурных ценностей"),
            ListItem.TextItem("Культурных феноменов"),
            ListItem.HeaderItem("Антропология"),
            ListItem.TextItem("Изучение человека"),
            ListItem.TextItem("Его происхождения"),
            ListItem.TextItem("Культуры"),
            ListItem.TextItem("Общества"),

            ListItem.MainHeaderItem("Физическая культура и спорт:"),
            ListItem.HeaderItem("Футбол"),
            ListItem.TextItem("Футбольная игра"),
            ListItem.TextItem("Тренировки"),
            ListItem.TextItem("Тактика"),
            ListItem.HeaderItem("Баскетбол"),
            ListItem.TextItem("Баскетбольная игра"),
            ListItem.TextItem("Тренировки"),
            ListItem.TextItem("Тактика"),
            ListItem.HeaderItem("Волейбол"),
            ListItem.TextItem("Волейбольная игра"),
            ListItem.TextItem("Тренировки"),
            ListItem.TextItem("Тактика"),
            ListItem.HeaderItem("Теннис"),
            ListItem.TextItem("Теннисная игра"),
            ListItem.TextItem("Тренировки"),
            ListItem.TextItem("Техника"),
            ListItem.HeaderItem("Плавание"),
            ListItem.TextItem("Различные стили плавания"),
            ListItem.TextItem("Тренировки"),
            ListItem.TextItem("Техника"),
            ListItem.HeaderItem("Боевые искусства"),
            ListItem.TextItem("Карате"),
            ListItem.TextItem("Дзюдо"),
            ListItem.TextItem("Бокс"),
            ListItem.TextItem("Кикбоксинг"),
            ListItem.TextItem("Айкидо"),
            ListItem.HeaderItem("Физическая подготовка"),
            ListItem.TextItem("Тренировки"),
            ListItem.TextItem("Фитнес"),
            ListItem.TextItem("Йога"),
            ListItem.TextItem("Пилатес"),
            ListItem.HeaderItem("Трек и поле"),
            ListItem.TextItem("Бег"),
            ListItem.TextItem("Прыжки"),
            ListItem.TextItem("Метания"),

            ListItem.MainHeaderItem("Другие направления:"),
            ListItem.HeaderItem("Кулинария"),
            ListItem.TextItem("Приготовление пищи"),
            ListItem.TextItem("Кулинарные техники"),
            ListItem.TextItem("Рецепты"),
            ListItem.HeaderItem("Садоводство"),
            ListItem.TextItem("Выращивание растений"),
            ListItem.TextItem("Уход за садом"),
            ListItem.TextItem("Дизайн сада"),
            ListItem.HeaderItem("Путешествия"),
            ListItem.TextItem("Посещение различных стран"),
            ListItem.TextItem("Изучение культур"),
            ListItem.TextItem("Языков"),
            ListItem.HeaderItem("Изучение языков"),
            ListItem.TextItem("Английский"),
            ListItem.TextItem("Испанский"),
            ListItem.TextItem("Французский"),
            ListItem.TextItem("Немецкий"),
            ListItem.TextItem("Китайский"),
            ListItem.HeaderItem("Волонтерство"),
            ListItem.TextItem("Помощь нуждающимся"),
            ListItem.TextItem("Участие в социальных проектах"),
            ListItem.TextItem("Предпринимательство"),
            ListItem.TextItem("Создание собственного бизнеса"),
            ListItem.TextItem("Разработка бизнес-планов"),
            ListItem.TextItem("Управление бизнесом")
        )
    }
}
// :, , драматургия,